<a href="https://colab.research.google.com/github/vasist05/eda-colab-lab/blob/main/numpy_lab_011.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Fundamentals-week1

THIS IS MY FIRST NUMPY lab PROGRAMS

In [ ]:
#a. Create a 1D array with numbers from 10 to 20.
import numpy as np #aliacing
a=np.arange(10,21)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]

In [ ]:
#b. Create a 3 × 4 array filled with 0s using nested lists.
import numpy as np
b=np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print(b)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

In [ ]:
#c. Create a 2 × 3 × 2 array using nested lists
c=np.array([[[1,2],[1,2],[1,2]],[[1,2],[1,2],[1,2]]])
print(c)

[[[1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]]]

In [ ]:
#d. Print all the arrays. Also print their shape and number of dimensions (ndim).
print(a)

print(b)

print(c)
print("shape of array a is :" ,a.shape)
print("shape of array b is :",b.shape)
print("shape of array c is :",c.shape)
print("dimension of array a is :" ,a.ndim)
print("dimension of array b is :",b.ndim)
print("dimension of array c is :",c.ndim)

[10 11 12 13 14 15 16 17 18 19 20]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]]]
shape of array a is : (11,)
shape of array b is : (3, 4)
shape of array c is : (2, 3, 2)
dimension of array a is : 1
dimension of array b is : 2
dimension of array c is : 3

2.  Create Arrays Using NumPy Functions

In [ ]:
#a. Create a 1D array of 6 elements, all filled with 7.
d=np.full(6,7)
print(d)

[7 7 7 7 7 7]

In [ ]:
#b. Print the array along with its shape and data type.
print("shape and data type of array d is",d.shape, "and",d.dtype)

shape and data type of array d is (6,) and int64

In [ ]:
#c. Create an array from 0 to 30 (excluding 30) with a step of 3 using arange().
e=np.arange(0,30,3)
print(e)

[ 0  3  6  9 12 15 18 21 24 27]

# **NumPy Fundamentals-week 2**
Write Python programs using NumPy to perform indexing, slicing and arithmetic operations.

 **Exercise 1: Basic Indexing**
Create a 1D NumPy array containing the elements [12, 25, 38, 47, 59, 61] and a 3 × 3 NumPy array containing the values from 10 to 90. Perform the following operations:
<hr>
1)Display the first and last elements of the 1D array.
<br>
2)Access the fourth element of the 1D array.
<br>
3)Retrieve the element at the first row and third column of the 2D array.<br>
4)Retrieve the element at the third row and second column.<br>
5)Display the last element of the 2D array using negative indexing.

1)Display the first and last elements of the 1D array.

In [ ]:
import numpy as np
arr=np.array([12, 25, 38, 47, 59, 61] )
arr
f=arr[0]
l=arr[-1]
print("the first and last element are:",f," ",l)

the first and last element are: 12   61

2)Access the fourth element of the 1D array

In [ ]:
print("the fourth element of the 1d array is :",arr[3])

the fourth element of the 1d array is : 47

In [ ]:
arr2d=np.array([11,21,84,56,32,74,14,55,63]).reshape(3,3)
print(arr2d)
print()
#3)Retrieve the element at the first row and third column of the 2D array.
print("the element at the first row and third column of the 2D array is :",arr2d[0,2])

[[11 21 84]
 [56 32 74]
 [14 55 63]]

the element at the first row and third column of the 2D array is : 84

In [ ]:
#4)Retrieve the element at the third row and second column.
print(" the element at the third row and second column:",arr2d[2,1])

 the element at the third row and second column: 55

In [ ]:
#5)Display the last element of the 2D array using negative indexing
print(" the last element of the 2D array using negative indexing is :",arr2d[-1,-1])

 the last element of the 2D array using negative indexing is : 63

##Exercise 2: Array Slicing
#### Create a 5 × 5 NumPy array containing integers from 1 to 25. <br>
Using slicing operations:

In [ ]:
#Extract the first row.
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print(arr,"\n")
print(" the first row is:",arr[0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 the first row is: [1 2 3 4 5]

In [ ]:
#Extract the last column.
print("the last column is:",arr[:,4])
print("the last column is:",arr[:,-1])

the last column is: [ 5 10 15 20 25]
the last column is: [ 5 10 15 20 25]

In [ ]:
#Display rows 2 to 4.
print("the elements in rows 2 to 4 are:\n",arr[2:5])

the elements in rows 2 to 4 are:
 [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

In [ ]:
#Extract the middle 3 × 3 subarray
print(arr[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

In [ ]:
#Display alternate rows.
print(arr[::2])#odd alternating rows
print()
print(arr[1::2])#even alternating rows

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]

[[ 6  7  8  9 10]
 [16 17 18 19 20]]

In [ ]:
#Extract the first three columns.
print(arr[:,0:3])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]

##Exercise 3: Boolean Indexing
<hr>
Create a NumPy array representing students' marks: [45, 68, 91, 34, 82, 76, 59,99, 41].
<hr>
 Using boolean indexing:
Display marks greater than 75.<br>
Display marks less than 40.<br>
Display all even marks.<br>
Display marks between 50 and 80 (inclusive).<br>
Count the number of students scoring above 60.

In [ ]:
import numpy as np
arr=np.array( [45, 68, 91, 34, 82, 76, 59, 99, 41])
m1=arr>75
print(m1,"\n")
#Using boolean indexing: Display marks greater than 75.
print(arr[m1])

[False False  True False  True  True False  True False]

[91 82 76 99]

In [ ]:
#Display marks less than 40.
m2=arr<40
print(m2,"\n")
print(arr[m2])

[False False False  True False False False False False]

[34]

In [ ]:
#Display all even marks
print(arr[arr%2==0])

[68 34 82 76]

In [ ]:
#Display marks between 50 and 80 (inclusive).
m3=(arr>=50) & (arr<=80)
print(m3,"\n")
print(arr[m3])

[False  True False False False  True  True False False]

[68 76 59]

In [ ]:
#Count the number of students scoring above 60.
m4=arr>60
a=arr[m4]
print(len(a))
a

5

array([68, 91, 82, 76, 99])

## Exercise 4: Fancy Indexing


---

Create a 1D NumPy array containing the elements:
 [11, 22, 33, 44, 55, 66, 77, 88, 99] and a 3 × 3 matrix.
<hr>

In [ ]:
import numpy as np
arr=np.array([11, 22, 33, 44, 55, 66, 77, 88, 99] )
arr

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [ ]:
#Perform the following using fancy indexing:
#Retrieve the elements at indices 0, 2, 4, 6, and 8.
l=[0,2,4,6,8]
print(arr[l])

[11 33 55 77 99]

In [ ]:
#Select the first and third rows of the matrix.
arr=arr.reshape(3,3)
print(arr,"\n")
l=[0,2]
print("the 1 st and 3rd rows are:\n",arr[l])

[[11 22 33]
 [44 55 66]
 [77 88 99]]

the 1 st and 3rd rows are:
 [[11 22 33]
 [77 88 99]]

In [ ]:
#Retrieve the diagonal elements using index arrays.
rows=[0,1,2]
col=[0,1,2]
print("the diagonal elements are:\n")
print(arr[rows,col])

the diagonal elements are:

[11 55 99]

In [ ]:
#Extract the corner elements of the matrix.
row=[0,0,2,2]
col=[0,2,0,2]
print(arr[row,col])

[11 33 77 99]

In [ ]:
#Rearrange the rows of the matrix in the order 3, 1, 2.
r3=arr[2]
r1=arr[0]
r2=arr[1]
narr=np.array([r3,r1,r2])
print(narr)

[[77 88 99]
 [11 22 33]
 [44 55 66]]

##Exercise 5: Combined Indexing Techniques<hr>
A company's quarterly sales data for four branches is stored in a 4 × 4 NumPy array.
 Perform the following operations:

In [ ]:
arr=np.arange(100,116).reshape(4,4)
arr

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115]])

In [ ]:
#Retrieve the sales value of the second branch during the third quarter
print(arr[1,2])

106

In [ ]:
#Display the sales data of the first two branches
print(arr[:2])

[[100 101 102 103]
 [104 105 106 107]]

In [ ]:
#Extract the sales values greater than 200 using boolean indexing
b1=arr>200
b1
print(arr[b1])

[]

In [ ]:
#Retrieve the sales values corresponding to the following positions using fancy indexing:
#(1st row, 2nd column)
#(3rd row, 4th column)
#(4th row, 1st column)

rows = [0, 2, 3]
cols = [1, 3, 0]
print(arr[rows, cols])

[101 111 112]

In [ ]:
#Display the last two quarters' sales for all branches using slicing.
print(arr[:,2:])

[[102 103]
 [106 107]
 [110 111]
 [114 115]]

#Week-3: (28/7/2026, Tue) : Advanced NumPy Operations

##Write Python programs using Transposition and reshaping arrays, Random number generation, Aggregate functions and axis operations

##Exercise 1: Transposition & Reshaping arrays

In [ ]:
#1.     Create a 3×4 NumPy array with integers from 0 to 11. Transpose the array using .T and verify the shape becomes 4×3. Print both arrays and observe the structural changes. (Transposing 2D Matrix)
import numpy as np
arr=np.arange(0,12).reshape(3,4)
transarr=arr.T
print(transarr)
print()
print(arr)
print("shape of arr is:",arr.shape)
print()
print("shape of arr is:",transarr.shape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape of arr is: (3, 4)

shape of arr is: (4, 3)

In [ ]:
#2. Create a 3D array of shape (2, 3, 4) with sequential numbers using np.arange() and reshape. Transpose it using .transpose(1, 0, 2) to reorder the shape as (3, 2, 4). (Transpose a 3-D Array)
# Print the new shape and verify that data was rearranged accordingly.
arr=np.arange(0,24).reshape(2,3,4)
print(arr)
print()
transarr=arr.transpose(1,0,2)
print(transarr)
print()
print("shape of transarr is:",transarr.shape)
print()

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

shape of transarr is: (3, 2, 4)

In [ ]:
#4. 	Generate a 6×2 array. Transpose it using .T, and then apply np.swapaxes(array, 0, 1) on the original array.
#Show that both results are the same and explain why. (Compare Transpose and Swapaxes)
arr=np.arange(0,12).reshape(6,2)
arr1=arr.T
arr2=np.swapaxes(arr,0,1)
print(arr1)
print()
print(arr2)
print(arr1==arr2)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]

In [ ]:
#5. 	Create a 3D array with shape (2, 4, 3). Use np.swapaxes to swap axes 0 and 2, and print the new shape.
# Check how the data has been reorganized by printing slices from both arrays. (Swapaxes on a 3D Array)
arr=np.arange(1,25).reshape(2,4,3)
print(arr)
arr2=np.swapaxes(arr,2,0)
print(arr2)
print("shape of arr2 is:",arr2.shape)
print()
print(arr[1,1])
print(arr2[1,1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
[[[ 1 13]
  [ 4 16]
  [ 7 19]
  [10 22]]

 [[ 2 14]
  [ 5 17]
  [ 8 20]
  [11 23]]

 [[ 3 15]
  [ 6 18]
  [ 9 21]
  [12 24]]]
shape of arr2 is: (3, 4, 2)

[16 17 18]
[ 5 17]

##Exercise 2: Random Number Generation

In [ ]:
#Use np.random.permutation to generate multiple random permutations of an array containing integers from 1 to 20.
#Ensure the original array remains unchanged after each permutation.
arr=np.arange(1,21)
rng=np.random.default_rng()
arr2=rng.permutation(arr)
arr2
print(arr)
print()
print(arr2)
print()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[ 7 16 10  1  8  3 18  4  9  2 17 12 20 19  5  6 14 13 15 11]

In [ ]:
# Using np.random.shuffle, create an array of characters ['A', 'B', 'C', 'D', 'E'] and shuffle its elements in-place.
#Print the array before and after shuffling to confirm it was modified.
arr=np.array(['A', 'B', 'C', 'D', 'E'])
arr2=rng.shuffle(arr)
print(arr2)
print(arr)

None
['A' 'B' 'E' 'C' 'D']

In [ ]:
 #Create a 5×4 matrix of random integers between 10 and 99 using np.random.randint.
 #Find the maximum value in each row and count how many values in the matrix are greater than 50.
 arr=np.random.randint(10,99,20).reshape(5,4)
 print(arr)
 maxi=arr.max(axis=1)
 maxi
 x=np.sum(arr>50)
 x

[[95 87 72 69]
 [38 58 78 12]
 [12 50 60 84]
 [76 25 16 46]
 [94 47 15 27]]

np.int64(10)

In [ ]:
 #Use np.random.standard_normal to generate a 6×6 matrix of normally distributed random numbers with mean 0 and standard deviation 1.
 # Compute and display the sample mean and standard deviation.
 arr=np.random.standard_normal(36)
 mean=arr.mean(axis=0)
 mean

np.float64(-0.22671764705515957)

In [ ]:
# Use np.random.normal to generate 1000 random values from a normal distribution with a mean of 100 and standard deviation of 15.
arr=np.random.normal(100,15,1000)
arr

array([ 98.12701742,  81.47715988,  91.57758465,  88.12136021,
       106.86229148,  91.827312  , 121.99407902,  98.56990508,
        99.31546351, 112.60490068,  92.47772615, 127.18281971,
       105.5593376 ,  84.5750509 ,  79.61873417,  85.36102775,
        99.27760254, 106.84027982, 110.65316211,  94.69096024,
        88.27636485, 103.47293893,  95.25286447,  85.17522627,
       110.07668383, 112.48329901,  99.00230914, 107.889807  ,
       100.50820954, 108.40493528, 108.29905921, 106.28577413,
        88.95118389,  92.21763541, 103.99103858, 107.18877918,
        91.10173701, 123.45896697, 105.65625094,  80.34249365,
        92.10656863, 125.34163595,  98.27011885,  95.0081868 ,
        99.58771835, 121.99683943,  82.09083733, 102.2495675 ,
        91.41065766,  80.76677456,  93.68040687, 117.68228836,
        98.77631723,  73.16751659,  85.09922724,  93.91658596,
        84.19890129,  90.00134791, 126.52779469,  91.74232106,
       103.83232404,  80.40925258, 108.53374691, 122.47500896,
       118.47487692,  98.81627278, 106.88646235,  77.78942033,
        78.34652191,  81.53306089, 100.10253696, 111.32332607,
       112.85552231,  99.080319  , 102.50215638,  71.84901289,
       110.66156071,  83.09467991,  94.24812179,  75.83434203,
        72.04551113, 101.0241969 , 107.35464221, 107.98500618,
        90.30283658, 101.17845311, 125.46240314,  93.40050684,
        97.3893059 ,  99.22230944, 112.13034122,  81.44830601,
       138.43794424, 111.25970368,  99.92464604, 104.44380864,
       103.61916909, 120.35785637, 108.27467569,  87.52364409,
        57.74078209,  96.88026694,  91.31029967, 122.1392229 ,
        95.00720659,  97.49375288,  97.07852694, 107.68586805,
        61.01841247, 118.92069303,  87.3744111 , 123.00281502,
       115.22244389, 109.03226346,  85.50800441,  87.31266479,
       107.46712429,  50.750125  ,  97.53655533,  93.68434495,
        87.23778485, 114.76258347, 102.94889869, 108.97720657,
       104.97574158, 125.01255147,  95.14728348,  91.24952249,
       101.8613732 , 114.89347153, 101.32527973,  89.4267898 ,
       113.29598147,  82.4022435 , 106.01600236,  92.81479233,
       121.72097638,  86.14571514, 118.62287017,  85.48329334,
        91.86456538,  97.36337224,  92.77084404,  95.15619258,
        94.39956808, 114.53524399, 123.2871276 , 102.35698749,
        85.7784621 , 100.69940359,  96.15476999,  84.82856871,
        82.44339174,  93.39165345,  78.69729041, 100.00897692,
       119.71567282, 117.19956692,  98.08951316, 104.37543414,
        86.05097703,  94.97464913,  92.0426368 , 108.41337813,
        99.57032503, 109.11165464, 106.30987965, 107.49857702,
       108.42282125,  94.47185846, 105.78808978, 107.22901659,
       139.94328363, 108.29738103,  97.03134454, 103.97567943,
        70.46038288,  91.64235475, 124.4284164 ,  96.75486877,
        84.58813968, 123.61567568, 101.47271426, 100.48775798,
        93.80074422, 105.41055383, 102.73970435, 111.45718588,
       105.2682981 , 111.49808346, 108.62987268, 108.67956763,
        92.32619962,  96.60349833,  94.44619217,  90.73693614,
        98.09413662, 117.84365209, 110.63083331,  76.84487356,
        99.17137081,  94.11370911,  81.94660112, 125.04703923,
        97.68549716, 119.7357289 ,  89.92579297,  91.80352862,
        97.05226315, 108.82406719,  88.57673722,  96.67933972,
       114.32330344, 110.8887413 ,  78.08565486,  84.28958181,
        96.92336004, 123.97917949,  92.35868462, 107.39767481,
        79.23913531,  81.97507943, 107.48476138,  75.39002083,
        91.1920384 , 128.29700159,  76.43493078,  96.62096022,
       107.07377853, 108.08872833,  84.92121981, 114.93780336,
        81.05811056, 109.57823682,  95.20825792,  95.95927065,
        85.31741634, 104.12393912,  92.60851444,  84.77206723,
       105.22792642,  72.49440454, 117.30864846,  65.09836134,
       101.30266214,  87.65825088, 103.14284654,  96.19425992,
        91.16937678, 100.22777463, 125.31839301, 101.95983717,
        88.2445198 , 106.64194934, 134.97342395, 100.97850529,
        90.37055204, 101.7559639 , 102.59877324, 104.02679201,
        92.55630477, 133.0861788 ,  91.47514532,  91.40205275,
        83.46906866,  88.15729125,  99.57495803, 117.45511155,
       115.99205365,  98.87576445, 105.19994028,  96.18873093,
        86.04816366,  85.73276323,  68.2979788 ,  99.69813599,
        97.16203852, 116.34325239,  90.73668895,  89.41961197,
       116.28924043,  86.99127107, 108.91785961,  89.07006318,
        81.20906444,  95.17755805, 116.66878778,  69.90734658,
       112.44812553, 139.99477052,  78.47457379,  82.81999753,
       108.05311473,  73.55696235,  88.98430592, 103.56791269,
       102.66481455, 131.32768585, 107.66625494, 107.48719346,
        79.50564472,  91.59459457,  89.72395127,  97.78885633,
        85.36382528, 126.89693964, 119.66958711, 106.34784707,
       109.45421537,  86.9295951 ,  88.1495982 , 101.80773318,
        88.38823956, 102.76594908,  88.15080719,  98.37233573,
       103.21134556, 115.03073922,  92.91674155,  88.69861283,
       107.16502375,  99.07712668, 100.40492276, 103.53216811,
       120.51286533,  87.23277273, 103.83846417,  70.48356269,
       101.40442181, 120.96896717,  99.31056294, 111.14228288,
       107.04699189, 102.30216772,  91.35310506,  99.94795044,
        97.64190055,  96.82210886,  89.39793911,  94.48951645,
       104.31280452,  79.11723808,  86.29177252, 103.93707599,
       109.15604986, 110.28472634,  98.55649011, 108.3270453 ,
       103.37386015, 120.2866791 ,  87.47258398, 106.59921578,
        81.18001444, 107.56462941, 102.6238143 , 117.6792207 ,
       112.38032459, 109.09972955,  85.90747223, 128.17223654,
       102.8718361 , 107.06230827,  85.60783064, 122.52226281,
       104.25592437, 105.94515652,  89.2098467 , 122.3364138 ,
        74.35561599, 119.77397449, 114.85473606,  99.73405449,
       106.75404283, 114.47342491,  97.27781781, 105.54224499,
       109.32973333, 112.34399525,  85.78768433,  89.66267222,
       103.00884265,  81.1589932 , 106.64132328, 111.32469106,
        89.94802375,  86.72633839, 103.24146265,  84.72760372,
       116.81913045, 100.87454484,  95.07775632, 128.7971094 ,
       101.80274733,  95.02415035, 116.76580999, 117.55071804,
        94.12473644, 113.68941942, 102.53433583,  83.83067479,
        87.95813018,  94.06294777,  84.81898557,  90.94705175,
        93.78061668,  88.92308348, 113.52597523, 117.97860617,
        88.16565631,  95.64558724, 102.66961091,  98.95490095,
        97.23095956, 111.292269  ,  91.22946866,  97.55411968,
        94.93035814, 102.26045183,  92.31766828, 100.7070151 ,
       112.64029803,  70.01383644,  96.93321607,  53.89646196,
       110.898032  , 127.75553854, 133.27242291, 110.57479581,
       102.84590556,  95.30149412, 122.43763681,  86.38939736,
        73.83231574, 113.48413383, 116.99649541, 108.58614372,
       125.75424694,  98.53378215, 107.42803461,  98.92291024,
       106.11524014, 115.29292291, 108.02060578,  93.15651136,
       107.90318554,  92.61407123,  94.50959466,  87.06367309,
       111.81050565, 104.14132413,  74.14960511,  85.84271177,
       108.76567729, 108.13451619,  85.92673392,  96.27021125,
       110.27602992, 153.97979204,  90.89223344, 112.30298032,
       116.41537447, 111.27506343, 104.03469758, 104.99309751,
       107.02435883, 101.99716365,  86.97496812,  95.7063603 ,
        95.59099172,  93.72322111, 126.16382488, 124.12194842,
       119.18012102, 108.82329098,  87.62406644,  83.50847283,
        80.79760929, 101.5938623 ,  91.54323005,  77.10918204,
       102.04674858, 103.35633156, 105.54042512, 110.37191414,
        84.04993717,  85.61512348,  91.29242974, 116.04783899,
        79.52596112, 102.06990255,  79.87553323,  83.54745401,
        89.6839842 ,  80.83721725, 124.01713511,  96.54841204,
       117.25106783, 106.05087815,  96.9860566 , 100.13338638,
       126.60585499,  86.65325125,  80.89224805,  88.1617783 ,
        87.1945601 , 136.63154802,  82.55849838,  84.1855582 ,
       103.47124195, 106.04080945,  96.78752056, 110.61121634,
        93.07030587, 108.5606218 , 100.46543353,  82.09597243,
        87.49260172,  97.22312785,  87.77319277, 111.72455357,
        94.70604834, 107.85743867, 146.11271798, 114.5636514 ,
        96.32274996, 107.07250299,  94.77701487,  92.68027396,
        92.12529274, 103.87179634,  85.10426052,  77.59042662,
       103.20733996, 111.55500493,  97.87163633,  61.36211311,
       113.98966073,  94.30704803, 115.85597137,  64.5584361 ,
       112.85842111,  98.31014195, 118.11838496, 107.88980718,
       101.33551663, 105.51235151,  79.55169642, 117.48002504,
        79.54920713, 121.42890544, 103.55960993, 103.01734857,
       109.33148883,  93.27797177, 101.13354431,  85.21615532,
        91.17360823, 102.7981723 ,  93.93987456,  90.6393349 ,
       110.69434045,  90.38577602, 108.24879314, 109.58399442,
        95.03855164, 100.48339361, 101.18970855,  94.66588378,
        93.8721266 , 103.01559216, 104.36393681,  94.09812284,
       112.90457997,  76.29346764,  78.23269091, 107.92561437,
       106.42710755,  83.21241868, 106.16610397, 131.83003741,
        87.63759507, 121.10220599,  87.61665837,  89.29406595,
       113.43925529,  97.66635898,  92.73092746, 125.40290411,
        83.22414178, 112.12034081, 114.40245458, 104.24019263,
        66.74155711, 101.57351639,  89.96787849,  90.52566722,
        88.18160839,  73.85972102,  74.6533084 ,  59.10025372,
       113.82989019,  83.55581373, 124.00139885,  99.77665205,
       102.9865351 ,  73.73133065,  85.32006137,  97.36148066,
       111.72039798,  98.06014496, 117.39759375,  81.95791366,
        96.03567016,  68.57681735,  89.94609587,  93.87128026,
       101.71762255, 102.67010767, 105.58072909, 118.51324912,
        97.9354549 , 101.5858107 ,  90.21142067,  84.06261012,
       129.6647049 ,  73.68463439,  94.00883874,  72.80326729,
       111.52686877,  71.64927517, 100.36506213,  95.19558312,
       104.63845113,  99.79820639,  89.28281825,  93.91911835,
        96.99824192,  73.28470942,  91.16273433, 101.61827226,
        91.27741986,  85.13552479,  67.12525626, 100.62130544,
       109.55031262,  79.1495973 ,  82.70250672,  82.72447641,
       107.52637245, 110.6946164 , 105.69327375,  96.14340301,
        94.29671423,  96.10080959, 123.87441364,  90.61022974,
        80.96508372,  86.80795365, 105.58657062,  94.39320707,
       149.43367508,  84.13236833,  88.92563006,  99.00254074,
        79.45083692, 102.81847347,  76.53835465,  93.21984383,
       132.65089583, 108.11935569, 123.15889323,  87.09594945,
        99.69453391,  97.35671567,  97.74317276, 116.00835045,
       105.22960524, 104.83908786, 106.89623869,  75.24985041,
       109.08338758,  93.04060224,  80.03368135, 113.89906485,
        98.39395161,  98.73714705,  87.05428352,  97.3103451 ,
        82.32569683, 101.32841786,  90.49518127,  92.54560541,
        96.54685954,  75.98736241,  89.23048122,  49.62348189,
        89.95339766,  95.28819447, 100.09300138,  89.20385928,
        74.6190159 ,  92.70522804,  91.19291497,  76.45907596,
       108.7815509 , 113.40316039, 122.88939553, 109.74762926,
        91.6130506 ,  98.43108117,  90.26643751,  88.82028823,
        90.08190254,  92.45251782,  95.89909514, 116.49796939,
        78.16588277,  86.24511774,  90.2041921 , 110.15613462,
        72.90068173,  99.53327719, 110.91469735,  94.12449239,
        88.98925565,  79.28800216, 108.4422818 , 102.76693679,
        68.4803841 , 116.50234781,  87.22093698, 118.61088016,
       106.46654169, 108.39077193, 119.10916449,  82.25698048,
        84.94579162,  83.94038843, 103.5746538 ,  92.25526426,
        81.48700768,  88.11214414, 106.86771191,  84.66543962,
        92.88403353, 115.22837287, 126.06373027,  89.48101823,
        79.16932039, 117.23169659,  87.42665482, 115.9156978 ,
       123.24355925, 116.55458122,  95.13558045, 102.52392056,
       100.87891505, 125.98090143,  69.74603749,  86.79388722,
       122.4215871 ,  95.77212221,  94.61343426,  90.61064695,
       111.43242075, 117.30296508,  93.07526148, 101.59279404,
       103.126152  , 108.26998541,  86.82275683,  85.51300388,
        95.64594232,  85.59753336,  98.70633948, 126.0025342 ,
       121.17831859, 114.25529362, 108.5639136 , 123.43330923,
        88.2328277 ,  82.56558459, 114.90141538,  63.14635808,
        98.76719377,  78.92758822,  88.91355739,  83.29315914,
       129.78768718, 101.68045805,  98.163543  , 105.37924352,
        82.53815995,  81.06377215, 111.47164676,  76.97532391,
       115.21017106,  94.03901576,  98.36817988,  83.88532872,
       108.03612795, 107.06128128, 102.08517298, 104.73261124,
       108.04242152,  89.58561   ,  78.74026005, 132.47883884,
        89.57416568, 106.31514708,  98.77908628, 114.91842993,
       119.58322346, 119.4937175 ,  93.0143033 , 110.01329739,
        93.09094015,  91.74815691, 103.8539217 ,  87.78000628,
        84.20025815,  83.59353363, 131.38208545,  88.05956104,
       102.00768158, 112.41486468,  88.49289666, 101.18487498,
       114.53742243,  89.77208852,  96.35512468,  98.00738709,
        99.76022053, 110.05411876,  76.56189901,  92.79784062,
        94.02193748, 100.63896576,  69.945248  ,  90.42142186,
        88.44775489, 134.28525341, 124.90930173,  92.01496212,
       114.92153464, 114.19138532, 110.96771235,  86.14968682,
       111.56357327,  87.03206667, 105.44926605, 115.51223831,
        85.64533733, 101.66954495,  79.43324271, 115.53931692,
       109.47570006,  94.94497983,  90.24881735,  82.03414339,
       129.09635406,  72.09095272, 101.58453624, 113.79468137,
       102.10459874,  79.74518053,  96.42038526,  93.50404557,
       126.8275009 ,  98.33141825,  91.29740772, 116.08716977,
       109.35777947, 124.26839297,  85.65464687,  89.90614654,
       105.45878782,  66.11042809, 105.84304225, 104.45585901,
        65.59831348, 100.56677159, 105.76577026, 100.45467354,
        99.75638469,  96.30542383,  84.78134554, 114.801014  ,
        91.6671354 , 107.41170774, 100.7602095 , 107.98138914,
       100.51404497,  92.91480466, 116.05909725, 111.82313169,
        82.7726306 ,  98.66521923, 101.87077279,  95.03150923,
        96.61066597, 111.17821176,  89.93780095,  93.55834023,
       120.50897674, 117.54418513, 118.87922706, 107.00234213,
        99.74531378,  96.57536165, 106.4472917 , 108.40504573,
        92.26941283, 133.38950311, 122.21473525,  93.13974953,
        90.57246455,  88.43140099, 108.852411  , 104.71333766,
       117.17230683, 103.27003543,  84.63602922, 115.75354603,
        92.85995591,  91.51673771,  68.24577983, 127.89594459,
       112.59083297,  84.64940433, 109.92508915,  86.52853726,
        85.24225665,  97.46800386, 108.16955009,  89.13991401,
       102.5442511 , 132.15252772, 104.20607498,  98.56734029,
        90.98981402, 100.02749422,  91.68909166,  78.078671  ,
        91.01013219,  95.61114566, 105.19763775,  98.68326641,
       103.27348001,  86.80795307, 105.31886903,  96.71949272,
        64.58351321,  88.20961543, 114.51985699, 106.82629832,
        87.74641683,  99.48674185, 114.94606775,  92.25928301,
        71.30682821,  88.31969369,  80.74815831,  97.62877645,
       100.56752163,  72.0778476 ,  94.3934622 , 106.28172998,
       105.01454048,  85.43220813,  90.12005415,  71.76743508,
       116.27728591, 109.42772467, 116.67206495,  92.66615692,
        97.2506665 , 122.43741052, 112.91559982, 105.56272065,
       108.27697081,  93.83127746, 111.90857016,  96.66137418,
       108.54791869, 104.75124432,  87.4390551 ,  98.48087487,
        78.62418898, 112.03903086,  92.2477249 , 100.32645623,
       117.0315724 ,  96.57365666,  96.50728464,  74.46020904,
       104.21179719, 103.82193144, 107.24246286,  95.68057642])

## Exercise 3: Aggregate functions and Axis Operations

In [ ]:
#Create a 5×4 NumPy array of random integers between 10 and 50, then
# compute row-wise sums, column-wise sums, and identify the row with the highest sum.
import numpy as np
rng=np.random.default_rng()
arr=random.randint(low=10,high=51,size=(5,4))
print(arr)
print("rsum is :",arr.sum(axis=1))
print("csum is:",arr.sum(axis=0))
rarr=arr.sum(axis=1)
print("row with highest sum is:",rarr.argmax())

[[40 37 15 31]
 [30 42 49 31]
 [23 35 10 26]
 [41 22 48 30]
 [46 26 32 13]]
rsum is : [123 152  94 141 117]
csum is: [180 162 154 131]
row with highest sum is: 1

In [ ]:
#Generate a 6×4 NumPy array of random integers between 50 and 100, then find row-wise means, column-wise means, column-wise standard deviations,
# and determine the column with the highest standard deviation.
arr=random.randint(low=50,high=101,size=(6,4))
print(arr)
rmean=arr.mean(axis=1)
print(rmean)
cmean=arr.mean(axis=0)
print(cmean)
rstd_dev=arr.std(axis=1)
print(rstd_dev)
cstd_dev=arr.std(axis=0)
print(cstd_dev)
print("the column with higest std deviation is:",cstd_dev.argmax())
#argmax() gives us index with max element

[[73 77 67 88]
 [65 69 90 73]
 [71 70 66 59]
 [81 61 92 76]
 [83 97 68 56]
 [89 68 84 77]]
[76.25 74.25 66.5  77.5  76.   79.5 ]
[77.         73.66666667 77.83333333 71.5       ]
[ 7.66077672  9.52299848  4.71699057 11.1467484  15.44344521  7.88986692]
[ 8.08290377 11.426091   11.11180553 10.9658561 ]
the column with higest std deviation is: 1

In [ ]:
#Create a 6×6 NumPy array of random floats from a normal distribution (mean 0, standard deviation 1),
# then for each column calculate (max - min) and identify the column with the largest range.
import numpy as np
rng=np.random.default_rng()
arr=rng.standard_normal(size=(6,6))
cmax=arr.max(axis=0)
cmin=arr.min(axis=1)
#print("max value in each col is:",cmax)
#print("min value in each col is:",cmin)
range=cmax-cmin
print("the range of cols is :",range)
print("the column with largest range is:",range.argmax())

the range of cols is : [1.49319472 1.97690653 2.37733771 0.47975411 2.95685362 2.2899882 ]
the column with largest range is: 4

In [ ]:
#Create a 1D NumPy array of 12 random integers between 100 and 500,
#then compute the cumulative sum, cumulative product, and cumulative maximum of its elements.
arr=random.randint(low=100,high=500,size=12)
print("the orginal array:",arr)
cumsum=arr.cumsum()
print("the cumulative sum of array is:",arr.cumsum())
print("the cumulative product of array is:",arr.cumprod())
print("the cumulative maximum of its elements is :",cumsum.argmax())

the orginal array: [138 282 157 336 196 126 329 244 124 438 173 194]
the cumulative sum of array is: [ 138  420  577  913 1109 1235 1564 1808 1932 2370 2543 2737]
the cumulative product of array is: [                 138                38916              6109812
           2052896832         402367779072       50698340163072
    16679753913650688  4069859954930767872  6600544421257322496
 -5100363061692350464  3080905865281847296  7399927505972723712]
the cumulative maximum of its elements is : 11

# Week-4: (4/8/2026, Tue) : Series and Data Frame creation

In [ ]:
#Create a pandas Series object of 10 random integers and display its attributes (index, values, dtype, size, shape).
import pandas as pd
import numpy as np
s=pd.Series(np.random.randint(1,100,size=10))
print(s)

print("the index values are:",s.index)
print("the values in series obj are:",s.values)
print("dtype:",s.dtype)
print("size:",s.size)
print("shape:",s.shape)

0    15
1    17
2    57
3    37
4    99
5    25
6    66
7    49
8    34
9    42
dtype: int64
the index values are: RangeIndex(start=0, stop=10, step=1)
the values in series obj are: [15 17 57 37 99 25 66 49 34 42]
dtype: int64
size: 10
shape: (10,)

In [ ]:
#Create a students DataFrame with columns Name, RollNo, Marks1, Marks2, Marks3 from lists/arrays/Dictionary and display the first 5 rows.
import pandas as pd
data = {
    "Name": ["vaist", "geeetha", "sohan", "gopika", "vaibhav", "maanvitha","ujjwal"],
    "Rollno": [11,12,13,18,16,52,61],
    "Marks1": [85, 90, 78, 88, 92, 80,96],
    "Marks2": [82, 95, 75, 91, 89, 84,45],
    "Marks3": [88, 93, 80, 90, 94, 86,91]
}
students = pd.DataFrame(data)
#print(students)
print(students.head(5))

      Name  Rollno  Marks1  Marks2  Marks3
0    vaist      11      85      82      88
1  geeetha      12      90      95      93
2    sohan      13      78      75      80
3   gopika      18      88      91      90
4  vaibhav      16      92      89      94

In [ ]:
#Create a DataFrame by loading any relevant dataset from Kaggle in .CSV format and display the first 3 rows of the DataFrame,
# display its index, shape, dimension and the number of columns. (Hint: df.head(10))
#from google.colab import files
#uploaded = files.upload()
df=pd.read_csv('/content/sample(011).csv.csv')
print(df.head(3))
print("Index:", df.index)
print("Shape:", df.shape)
print("Dimension:", df.ndim)
print("Number of Columns:", len(df.columns))

    result  table                  timestamp                        member  \
0  _result      0  2026-07-03 08:09:43+00:00  4Y4tgCUKVoTbvnVrrN8AETclnTG2
1  _result      0  2026-07-03 08:10:44+00:00  4Y4tgCUKVoTbvnVrrN8AETclnTG2
2  _result      0  2026-07-03 08:11:46+00:00  4Y4tgCUKVoTbvnVrrN8AETclnTG2

    humidity  temperature
0  42.900002    26.299999
1  42.799999    26.299999
2  42.799999    26.299999
Index: RangeIndex(start=0, stop=260788, step=1)
Shape: (260788, 6)
Dimension: 2
Number of Columns: 6

#week 5-Series and Data Frame creation-11/08/26

###creating dataframe

In [39]:
import pandas as pd
df=pd.read_csv('/content/sleep_doomscrolling_habits.csv')

df

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
0,D30000,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,...,Unemployed,Germany,Tablet,Meditation/Journaling,Yes,Yes,Yes,No,Yes,Good
1,D30001,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,...,Student,India,Smartphone,Meditation/Journaling,No,Yes,Yes,No,Yes,Poor
2,D30002,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,...,Student,India,Laptop,Reading,No,Yes,No,Yes,Yes,Fair
3,D30003,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,...,NaN,United States,Smartphone,No Fixed Routine,No,Yes,Yes,No,No,Fair
4,D30004,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,...,Employed Part-time,United States,Smartphone,Watching Videos,No,No,No,No,No,Fair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,D30995,26,85.0,3.56,4,25.4,7.6,34.0,1,169.0,...,Student,India,Tablet,Meditation/Journaling,No,Yes,Yes,Yes,Yes,Poor
996,D30996,23,3.0,1.10,1,10.7,7.5,31.0,1,34.0,...,Student,United States,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Fair
997,D30997,15,28.0,4.38,1,30.6,9.2,20.0,0,100.0,...,Employed Full-time,United States,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Good
998,D30998,22,23.0,1.84,0,27.9,6.9,41.0,2,45.0,...,Student,India,Tablet,Watching Videos,No,Yes,Yes,Yes,No,Fair
999,D30999,23,35.0,1.66,2,16.2,7.5,27.0,2,63.0,...,Employed Full-time,India,Tablet,Scrolling Social Media,No,Yes,Yes,No,Yes,Fair

###problems

In [40]:
#1)Perform label-based (.loc) to select specific students’ details and marks and positional
 #(.iloc) indexing to slice rows 2–5 with selected columns.

print(df.loc[[2,3,5,433],["age","total_daily_screen_time_hours"]])#selecting specific students
df.iloc[1:5,[5,10,14,21,29]]

     age  total_daily_screen_time_hours
2     37                           5.15
3     27                           3.74
5     21                           5.20
433   25                           3.20

,avg_doomscroll_session_minutes,anxiety_score,number_of_news_apps_used,country_region,sleep_quality_category
1,29.6,5,2,India,Poor
2,15.5,2,0,India,Fair
3,51.4,6,1,United States,Fair
4,32.2,5,3,United States,Fair

In [41]:
#Use Boolean indexing to filter students with Marks1 > 70, calculate a Total column,
# and add a Result column with Pass/Fail status.
##"similar program"
d1=df[df['bedtime_screen_time_minutes']>150]#students whose bedtime screen time is more than 150 mins.
df["total"]=df["doomscroll_sessions_per_night"]+df['sleep_latency_minutes']+df['anxiety_score']
df
df["g/b"]=df["total"].apply(lambda x:"good" if x<=30 else "bad")##first we filtered in total col by using lambda function and.apply() and
                                                                #adding a new col using df["g/b"]=
df

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category,total,g/b
0,D30000,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,...,Tablet,Meditation/Journaling,Yes,Yes,Yes,No,Yes,Good,26.0,good
1,D30001,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,...,Smartphone,Meditation/Journaling,No,Yes,Yes,No,Yes,Poor,39.0,bad
2,D30002,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,...,Laptop,Reading,No,Yes,No,Yes,Yes,Fair,29.0,good
3,D30003,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,...,Smartphone,No Fixed Routine,No,Yes,Yes,No,No,Fair,41.0,bad
4,D30004,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,...,Smartphone,Watching Videos,No,No,No,No,No,Fair,26.0,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,D30995,26,85.0,3.56,4,25.4,7.6,34.0,1,169.0,...,Tablet,Meditation/Journaling,No,Yes,Yes,Yes,Yes,Poor,48.0,bad
996,D30996,23,3.0,1.10,1,10.7,7.5,31.0,1,34.0,...,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Fair,37.0,bad
997,D30997,15,28.0,4.38,1,30.6,9.2,20.0,0,100.0,...,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Good,24.0,good
998,D30998,22,23.0,1.84,0,27.9,6.9,41.0,2,45.0,...,Tablet,Watching Videos,No,Yes,Yes,Yes,No,Fair,44.0,bad
999,D30999,23,35.0,1.66,2,16.2,7.5,27.0,2,63.0,...,Tablet,Scrolling Social Media,No,Yes,Yes,No,Yes,Fair,37.0,bad

In [ ]:
#Display the DataFrame attributes shape, columns, index, ndim, and size.
print("shape:",df.shape)
print("size:",df.size)
print("index:",df.index)
print("ndim:",df.ndim)
print("columns:",df.columns)
df[2:10]

shape: (1000, 33)
size: 33000
index: RangeIndex(start=0, stop=1000, step=1)
ndim: 2
columns: Index(['respondent_id', 'age', 'bedtime_screen_time_minutes',
       'total_daily_screen_time_hours', 'doomscroll_sessions_per_night',
       'avg_doomscroll_session_minutes', 'sleep_hours_per_night',
       'sleep_latency_minutes', 'number_of_night_wakeups',
       'caffeine_intake_mg_per_day', 'anxiety_score', 'stress_score',
       'sleep_quality_score', 'daytime_fatigue_score',
       'number_of_news_apps_used', 'phone_checks_per_night',
       'exercise_minutes_per_day', 'days_since_last_digital_detox',
       'weekly_sleep_debt_hours', 'gender', 'occupation_status',
       'country_region', 'primary_device_used_at_night',
       'bedtime_routine_type', 'uses_night_mode', 'keeps_phone_in_bedroom',
       'consumes_negative_news_content', 'uses_sleep_tracking_app',
       'doomscroller', 'sleep_quality_category', 'total', 'g', 'g/b'],
      dtype='object')

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category,total,g,g/b
2,D30002,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,...,Reading,No,Yes,No,Yes,Yes,Fair,29.0,good,good
3,D30003,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,...,No Fixed Routine,No,Yes,Yes,No,No,Fair,41.0,bad,bad
4,D30004,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,...,Watching Videos,No,No,No,No,No,Fair,26.0,good,good
5,D30005,21,81.0,5.20,4,19.5,7.9,39.0,2,61.0,...,Watching Videos,No,Yes,No,No,Yes,Fair,48.0,bad,bad
6,D30006,34,56.0,3.75,3,18.7,8.8,45.0,1,166.0,...,Scrolling Social Media,No,Yes,No,No,Yes,Good,51.0,bad,bad
7,D30007,26,40.0,2.41,3,13.7,7.7,36.0,2,54.0,...,Scrolling Social Media,Yes,Yes,Yes,Yes,Yes,Poor,43.0,bad,bad
8,D30008,32,77.0,3.38,4,19.2,7.8,29.0,1,127.0,...,Reading,Yes,Yes,No,No,Yes,Fair,37.0,bad,bad
9,D30009,34,23.0,2.46,2,7.8,6.4,18.0,3,97.0,...,Reading,No,No,No,No,No,Poor,24.0,good,good

In [ ]:
#Use .loc and Boolean indexing to select students from the AI & DS department who have an average mark above 70.
#instead of ai&ds i will take india country region and total >15
f=df.loc[:,"country_region"]
a=df[df.loc[:,"country_region"]=="India"]
b=df.loc[df["country_region"]=="India"]

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category,total,g,g/b
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
992,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
995,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
998,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
999,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [ ]:
df.iloc[[-1,-2,-3]]

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category,total,g,g/b
999,D30999,23,35.0,1.66,2,16.2,7.5,27.0,2,63.0,...,Scrolling Social Media,No,Yes,Yes,No,Yes,Fair,37.0,bad,bad
998,D30998,22,23.0,1.84,0,27.9,6.9,41.0,2,45.0,...,Watching Videos,No,Yes,Yes,Yes,No,Fair,44.0,bad,bad
997,D30997,15,28.0,4.38,1,30.6,9.2,20.0,0,100.0,...,Scrolling Social Media,No,Yes,No,No,No,Good,24.0,good,good

In [ ]:

df.head(5)
df.tail(5)

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
995,D30995,26,85.0,3.56,4,25.4,7.6,34.0,1,169.0,...,Student,India,Tablet,Meditation/Journaling,No,Yes,Yes,Yes,Yes,Poor
996,D30996,23,3.0,1.10,1,10.7,7.5,31.0,1,34.0,...,Student,United States,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Fair
997,D30997,15,28.0,4.38,1,30.6,9.2,20.0,0,100.0,...,Employed Full-time,United States,Smartphone,Scrolling Social Media,No,Yes,No,No,No,Good
998,D30998,22,23.0,1.84,0,27.9,6.9,41.0,2,45.0,...,Student,India,Tablet,Watching Videos,No,Yes,Yes,Yes,No,Fair
999,D30999,23,35.0,1.66,2,16.2,7.5,27.0,2,63.0,...,Employed Full-time,India,Tablet,Scrolling Social Media,No,Yes,Yes,No,Yes,Fair

In [ ]:
!git clone https://github.com/vasist05/eda-colab-lab.git

fatal: destination path 'eda-colab-lab' already exists and is not an empty directory.
fatal: not a git repository (or any of the parent directories): .git

In [ ]:
%cd eda-colab-lab
!git status

/content/eda-colab-lab
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

#Week-6: (18/8/26, Tue) : Sorting, Ranking

1)Create a pandas.Series of student grades: ['A', 'B', 'C', 'A', 'D', 'B', 'C', 'F'].
 Map letter grades to numeric values using a dictionary:
 {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0}.
  Display the numeric grades.

In [8]:
import pandas as pd
s=pd.Series(['A', 'B', 'C', 'A', 'D', 'B', 'C', 'F'])
print(s)
#mapping
m=s.map( {'A': 4, 'B': 3, 'C': 2, 'D': 1, 'F': 0})
print(m)

0    A
1    B
2    C
3    A
4    D
5    B
6    C
7    F
dtype: object
0    4
1    3
2    2
3    4
4    1
5    3
6    2
7    0
dtype: int64

3)Create a DataFrame with columns:
  Name = ['Alice', 'Bob', 'Charlie', 'David', 'Eva']  Marks = [87, 45, 67, 92, 78]
<br> Sort the DataFrame:
<br>  By Marks in ascending order.
<br> By Marks in descending order.
<br> By Name alphabetically.

In [21]:
df1=pd.DataFrame({"Name":['Alice', 'Bob', 'Charlie', 'David', 'Eva'],"Marks":[87, 45, 67, 92, 78]})
# sorting by marks in ascde
df2=df1.sort_values("Marks")
print(df2,"\n")
# sorting by marks in descending
df3=df1.sort_values("Marks",ascending=False)
print(df3)
print()
df4=df1.sort_values("Name")
print(df4)

      Name  Marks
1      Bob     45
2  Charlie     67
4      Eva     78
0    Alice     87
3    David     92

      Name  Marks
3    David     92
0    Alice     87
4      Eva     78
2  Charlie     67
1      Bob     45

      Name  Marks
0    Alice     87
1      Bob     45
2  Charlie     67
3    David     92
4      Eva     78

Create a DataFrame of products with columns: ['Product', 'Price', 'Rating'].
<br>Sort first by Price (ascending), then by Rating (descending).

In [29]:
df5=pd.DataFrame({"product":["oreo","vim","benz","calc"],"price":[104,51,500000,2000],"rating":[3,4,5,2]})
print(df5,"\n")
df6=df5.sort_values("price")
print(df6,"\n")
df7=df5.sort_values("rating",ascending=False)
print(df7)

  product   price  rating
0    oreo     104       3
1     vim      51       4
2    benz  500000       5
3    calc    2000       2

  product   price  rating
1     vim      51       4
0    oreo     104       3
3    calc    2000       2
2    benz  500000       5

  product   price  rating
2    benz  500000       5
1     vim      51       4
0    oreo     104       3
3    calc    2000       2

###Ranking Data
a) Create a Series of student scores [87, 92, 45, 76, 92, 60].
<br>   Use rank() to assign ranks (average ranking method).
<br>   Use rank(method='first') and compare.

In [33]:

s = pd.Series([87, 92, 45, 76, 92, 60])
print(s)
print()
print(s.rank())
print()
print(s.rank(method='first'))

0    87
1    92
2    45
3    76
4    92
5    60
dtype: int64

0    4.0
1    5.5
2    1.0
3    3.0
4    5.5
5    2.0
dtype: float64

0    4.0
1    5.0
2    1.0
3    3.0
4    6.0
5    2.0
dtype: float64